import { DataSource } from 'typeorm';
import { Employee, ScheduleType } from '@/plants/employees/entities/employee.entity';
import { Field } from '@/plants/fields/entities/field.entity';

const FIELD_ID = '3d9cfab7-cb85-4e04-98ba-6d78fa410a20';

const employeesData: Partial<
  Employee>[] = [
  // ── 6x6 ──────────────────────────────────────────────────────────────────
  {
    identification_number: '7708530',
    first_name: 'MARIO ALEXANDER',
    last_name: 'QUIROGA SANCHEZ',
    position: 'RECORREDOR D',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3883320,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1075539865',
    first_name: 'EDWIN FABIAN',
    last_name: 'BELTRAN MOSQUERA',
    position: 'RECORREDOR D',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3883320,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1075255747',
    first_name: 'OSCAR LIBARDO',
    last_name: 'PASCUAS PASCUAS',
    position: 'RECORREDOR D',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3883320,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '7699950',
    first_name: 'WEIMAR',
    last_name: 'PARRA GARZON',
    position: 'RECORREDOR D',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3883320,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '7722865',
    first_name: 'DIEGO ANDRES',
    last_name: 'RAMIREZ MOSQUERA',
    position: 'RECORREDOR D (MOVIL 100)',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3883320,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '7685135',
    first_name: 'RUDECINDO',
    last_name: 'CHARRY GÓMEZ',
    position: 'RECORREDOR D (MOVIL 100)',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3883320,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    // Aparece en 6X6 y en 5X2 → ambos schedules
    identification_number: '1075545416',
    first_name: 'DIEGO ANDRES',
    last_name: 'CHARRY SARRIAS',
    position: 'AUXILIAR TRANSVERSAL B',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.SIX_BY_SIX, ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '7718043',
    first_name: 'DAGO',
    last_name: 'MEDINA',
    position: 'RECORREDOR D (MOVIL 100)',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3883320,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '12127748',
    first_name: 'JOSE',
    last_name: 'RAMIREZ',
    position: 'RECORREDOR D (MOVIL 100)',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3883320,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1072745477',
    first_name: 'FABER ANDRES',
    last_name: 'MONROY',
    position: 'OPERADOR MAYOR E',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4933050,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '83168985',
    first_name: 'UGALLIS',
    last_name: 'CHARRY ARIAS',
    position: 'OPERADOR MAYOR E',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4933050,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '7732490',
    first_name: 'ARNOLD',
    last_name: 'RAMIREZ RAMIREZ',
    position: 'OPERADOR MAYOR E',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4933050,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1075539839',
    first_name: 'JESUS EMILIO',
    last_name: 'LOSADA',
    position: 'OPERADOR MAYOR E',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4933050,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '7713313',
    first_name: 'CARLOS ANDRES',
    last_name: 'MORENO MOSQUERA',
    position: 'OPERADOR MAYOR E',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4933050,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1075540293',
    first_name: 'GERMÁN',
    last_name: 'RAMÍREZ AVILÉS',
    position: 'OPERADOR MAYOR E',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4933050,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1075539515',
    first_name: 'FAIVER',
    last_name: 'CHARRY ARIAS',
    position: 'OPERADOR MAYOR E',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4933050,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '36309786',
    first_name: 'BLANCA VIVIANA',
    last_name: 'GUZMAN',
    position: 'OPERADOR MAYOR E',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4933050,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '83169869',
    first_name: 'JORGE ANDRES',
    last_name: 'CHARRY CERQUERA',
    position: 'OPERADOR MAYOR E',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4933050,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '86046517',
    first_name: 'JUAN DE JESUS',
    last_name: 'HORTA',
    position: 'OPERADOR MAYOR E',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4933050,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '7693737',
    first_name: 'WILVER ADOLFO',
    last_name: 'GARZON ARIAS',
    position: 'OPERADOR MAYOR E',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4933050,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1075540661',
    first_name: 'RODRIGO ANDRES',
    last_name: 'GUTIERREZ QUINTANA',
    position: 'OPERADOR MAYOR E',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4933050,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  // ── 5x2 ──────────────────────────────────────────────────────────────────
  {
    identification_number: '1075269788',
    first_name: 'JHON EDINSSON',
    last_name: 'CHARRY VILLAREAL',
    position: 'MANTENEDOR MAYOR C',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 5519910,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '12132878',
    first_name: 'JAIME',
    last_name: 'PERDOMO OVIEDO',
    position: 'MANTENEDOR MAYOR C',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 5519910,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '7724898',
    first_name: 'JAIVER',
    last_name: 'MEDINA JOVEN',
    position: 'AYUDANTE TECNICO DE SOLDADURA - AYUDANTE TECNICO C',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '83169679',
    first_name: 'JORGE',
    last_name: 'LASSO DIAZ',
    position: 'AYUDANTE TECNICO DE SOLDADURA - AYUDANTE TECNICO C',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '16845159',
    first_name: 'ONEYDER',
    last_name: 'HERNÁNDEZ',
    position: 'MANTENEDOR MAYOR C (Tubero)',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 5519910,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '80254482',
    first_name: 'EVER',
    last_name: 'OSORIO OSORIO',
    position: 'OPERADOR EN ENTRENAMIENTO A',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3306720,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '7692434',
    first_name: 'JOSE LUIS',
    last_name: 'ARIAS',
    position: 'CAPATAZ CUADRILLA DE PRODUCCION',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1075280846',
    first_name: 'JOSE VICENTE',
    last_name: 'ALVAREZ ARIAS',
    position: 'CAPATAZ CUADRILLA DE PRODUCCION',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '7707115',
    first_name: 'YILBERT ALBERTO',
    last_name: 'LSADA',
    position: 'CAPATAZ CUADRILLA DE PRODUCCION',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '7729619',
    first_name: 'LEONARDO',
    last_name: 'CHARRY CHARRY',
    position: 'CAPATAZ CUADRILLA DE PRODUCCION',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '7713837',
    first_name: 'JESUS ANTONIO',
    last_name: 'MEDINA',
    position: 'AUXILIAR TRANSVERSAL B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1003809559',
    first_name: 'JOHAN SEBASTIAN',
    last_name: 'ZULETA',
    position: 'AUXILIAR TRANSVERSAL B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '7707983',
    first_name: 'HOLLMAN',
    last_name: 'FLOREZ CHAVARRO',
    position: 'AUXILIAR TRANSVERSAL B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1075544779',
    first_name: 'MAICOL STEVEN',
    last_name: 'VILLAREAL',
    position: 'AUXILIAR TRANSVERSAL B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '15437754',
    first_name: 'WILSON',
    last_name: 'VARIAZA',
    position: 'AUXILIAR TRANSVERSAL B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '7709196',
    first_name: 'BENIGNO',
    last_name: 'RAMIREZ MEDINA',
    position: 'AUXILIAR TRANSVERSAL B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '7703495',
    first_name: 'JAIME',
    last_name: 'MORENO PUENTES',
    position: 'AUXILIAR TRANSVERSAL B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '12136790',
    first_name: 'LUIS ALBERTO',
    last_name: 'ARIAS',
    position: 'AUXILIAR TRANSVERSAL B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1003819291',
    first_name: 'SEBASTIAN',
    last_name: 'RUIZ RAMIREZ',
    position: 'AUXILIAR TRANSVERSAL B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1003818400',
    first_name: 'CRISTIAN DAVID',
    last_name: 'RAMIREZ MORENO',
    position: 'AUXILIAR TRANSVERSAL B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1193126164',
    first_name: 'GUSTAVO ADOLFO',
    last_name: 'OSORIO',
    position: 'OBRERO A1',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3149280,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '96361044',
    first_name: 'JORGE ELIECER',
    last_name: 'PEREZ QUINTERO',
    position: 'OBRERO B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3149280,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1075545068',
    first_name: 'SEBASTIAN',
    last_name: 'ORTIZ HERMOSA',
    position: 'OBRERO B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3149280,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1075545441',
    first_name: 'CARLOS EDUARDO',
    last_name: 'MONTES SANCHEZ',
    position: 'OBRERO B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3149280,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1075795139',
    first_name: 'JHON NICOLÁS',
    last_name: 'RODRÍGUEZ MADRIGAL',
    position: 'OBRERO B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3149280,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '7726861',
    first_name: 'ISIDRO',
    last_name: 'CORTÉS CASTELLANOS',
    position: 'OBRERO B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3149280,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '83169175',
    first_name: 'DIEGO HERNAN',
    last_name: 'DIAZ CALDERON',
    position: 'OBRERO B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3149280,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1075538741',
    first_name: 'DIEGO ARMANDO',
    last_name: 'RINCON BONILLA',
    position: 'OFICIAL DE CONSTRUCCION A',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4077630,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1082214224',
    first_name: 'CRISTIAN CAMILO',
    last_name: 'CERQUERA MEJIA',
    position: 'HSEQ OPERATIVO',
    aux_trans: false,
    aux_hab: false,
    aux_ali: false,
    salario_base: 5519910,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '83248618',
    first_name: 'GERARDO',
    last_name: 'GUZMAN GARCIA',
    position: 'SUPERVISOR DE PRODUCCION',
    aux_trans: false,
    aux_hab: false,
    aux_ali: false,
    salario_base: 8177580,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '83238174',
    first_name: 'LUIS ALFREDO',
    last_name: 'GAHONA CUENCA',
    position: 'TECNICO TRANSVERSAL C',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4077630,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
];

export async function seedEmployeesDina(dataSource: DataSource): Promise<void> {
  const employeeRepo = dataSource.getRepository(Employee);
  const fieldRepo = dataSource.getRepository(Field);

  const field = await fieldRepo.findOneBy({ id: FIELD_ID });
  if (!field) {
    throw new Error(`Field with id ${FIELD_ID} not found. Run field seed first.`);
  }

  let created = 0;
  let skipped = 0;

  for (const data of employeesData) {
    const exists = await employeeRepo.findOneBy({
      identification_number: data.identification_number,
    });

    if (exists) {
      skipped++;
      continue;
    }

    const employee = employeeRepo.create({ ...data, field });
    await employeeRepo.save(employee);
    created++;
  }

  console.log(
    `✅ Employees seed complete — created: ${created}, skipped (already exist): ${skipped}`,
  );
}