import { DataSource } from 'typeorm';
import { Employee,ScheduleType } from '@/plants/employees/entities/employee.entity';
import { Field } from '@/plants/fields/entities/field.entity';

const FIELD_ID = '5d01608a-61db-412f-b714-ed461a124bec';

const employeesData: Partial<Employee>[] = [
  // ── 6x6 ──────────────────────────────────────────────────────────────────
  {
    identification_number: '7709176',
    first_name: 'CHRISTIAN EDUARDO',
    last_name: 'GOMEZ YUSUNGUAIRA',
    position: 'RECORREDOR B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1075265016',
    first_name: 'YERZON',
    last_name: 'GARZON DUSSAN',
    position: 'RECORREDOR B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1075284182',
    first_name: 'JHONY MAURICIO',
    last_name: 'CAMACHO MORA',
    position: 'RECORREDOR B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '7693562',
    first_name: 'RUBEN',
    last_name: 'MEDINA CARDOZO',
    position: 'RECORREDOR B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1075224885',
    first_name: 'ANDRES FELIPE',
    last_name: 'NARANJO CUMACO',
    position: 'RECORREDOR B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1075256009',
    first_name: 'CESAR EDUARDO',
    last_name: 'PASCUAS LASSO',
    position: 'RECORREDOR B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1075259849',
    first_name: 'FRANCISCO FERNANDO',
    last_name: 'GARZON CABRERA',
    position: 'RECORREDOR B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1003814711',
    first_name: 'SERGIO ANDRES',
    last_name: 'AROCA MEDINA',
    position: 'RECORREDOR B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1075254748',
    first_name: 'ALEJANDRO',
    last_name: 'PASCUAS GARCIA',
    position: 'OPERADOR REMOTO POZOS (SCADA)',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4933050,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1075258907',
    first_name: 'JHONY JHONATAN',
    last_name: 'CABEZAS AROCA',
    position: 'OPERADOR REMOTO POZOS (SCADA)',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4933050,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1075227346',
    first_name: 'OSCAR MAURICIO',
    last_name: 'CUMACO PASCUAS',
    position: 'OPERADOR REMOTO POZOS (SCADA)',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4933050,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1075265315',
    first_name: 'JHOAN MAURICIO',
    last_name: 'ALDANA VANEGAS',
    position: 'OPERADOR REMOTO POZOS (SCADA)',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4933050,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '17640798',
    first_name: 'JUAN CARLOS',
    last_name: 'REYES TRUJILLO',
    position: 'OPERADOR MAYOR C',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 5519910,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1075271841',
    first_name: 'JESUS ALBERTO',
    last_name: 'GARZON CABRERA',
    position: 'OPERADOR MAYOR C',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 5519910,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1075233154',
    first_name: 'EDWIN',
    last_name: 'LEAL MEDINA',
    position: 'OPERADOR MAYOR C',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 5519910,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '7705648',
    first_name: 'JAIVER MAURICIO',
    last_name: 'TRUJILLO BELTRAN',
    position: 'OPERADOR MAYOR C',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 5519910,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '83169917',
    first_name: 'EDINSON',
    last_name: 'CONDE RIVERA',
    position: 'RECORREDOR B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '7722376',
    first_name: 'JUAN GABRIEL',
    last_name: 'QUIROGA DIAZ',
    position: 'RECORREDOR B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '83168641',
    first_name: 'OSCAR',
    last_name: 'DIAZ RUBIANO',
    position: 'RECORREDOR B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '7724010',
    first_name: 'ALEX MAURICIO',
    last_name: 'PERDOMO CASTAÑEDA',
    position: 'RECORREDOR B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  // ── 5x2 ──────────────────────────────────────────────────────────────────
  {
    identification_number: '7723986',
    first_name: 'JUAN DIEGO',
    last_name: 'CABRERA',
    position: 'MANTENEDOR MAYOR B',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 5839140,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1075540477',
    first_name: 'CARLOS ANDRES',
    last_name: 'CABRERA',
    position: 'AYUDANTE TECNICO DE SOLDADURA - AYUDANTE TECNICO C',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '7726462',
    first_name: 'MICHEL',
    last_name: 'AROCA MEDINA',
    position: 'CAPATAZ CUADRILLA DE PRODUCCION',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '12139850',
    first_name: 'EDISSON',
    last_name: 'PASTRANA ALDANA',
    position: 'CAPATAZ CUADRILLA DE PRODUCCION',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '7689737',
    first_name: 'ALEXANDER',
    last_name: 'LASSO AROCA',
    position: 'AUXILIAR TRANSVERSAL B',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1075259577',
    first_name: 'DUVIER ALBERTO',
    last_name: 'CANACUE CANACUE',
    position: 'AUXILIAR TRANSVERSAL B',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '7722832',
    first_name: 'BETUEL',
    last_name: 'OLARTE DUSSAN',
    position: 'AUXILIAR TRANSVERSAL B',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '7692372',
    first_name: 'ALVARO',
    last_name: 'CANGREJO',
    position: 'AUXILIAR TRANSVERSAL B',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '7712700',
    first_name: 'WILLIN GREEY',
    last_name: 'PUENTES SAENZ',
    position: 'AUXILIAR TRANSVERSAL B',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1075309390',
    first_name: 'BRAYAN ESTIBEN',
    last_name: 'AROCA RODRIGUEZ',
    position: 'AUXILIAR TRANSVERSAL B',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1076500541',
    first_name: 'DANIEL FELIPE',
    last_name: 'TORRES DUSSAN',
    position: 'OBRERO B',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3149280,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1007465543',
    first_name: 'YORMAN DUVAN',
    last_name: 'DUSSAN CABRERA',
    position: 'OBRERO B',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3149280,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '7731226',
    first_name: 'CARLOS ENRIQUE',
    last_name: 'RAMIREZ TRUJILLO',
    position: 'OBRERO B',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3149280,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1003828739',
    first_name: 'JOSE DAWINSON',
    last_name: 'QUESADA ESPINOSA',
    position: 'OBRERO B',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3149280,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '7699798',
    first_name: 'JOHNN HAROLD',
    last_name: 'MOREA',
    position: 'HSE OPERATIVO',
    aux_trans: false,
    aux_hab: false,
    aux_ali: false,
    salario_base: 5519910,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1075288309',
    first_name: 'CARLOS ANDRES',
    last_name: 'FLOREZ CHAUX',
    position: 'SUPERVISOR DE PRODUCCION',
    aux_trans: false,
    aux_hab: false,
    aux_ali: false,
    salario_base: 8177580,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '80138883',
    first_name: 'JOHN ALEXANDER',
    last_name: 'GALINDO RIAÑO',
    position: 'CAPATAZ CUADRILLA DE PRODUCCION',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1075541374',
    first_name: 'MILLER JESUS',
    last_name: 'CHARRY ROA',
    position: 'AUXILIAR TRANSVERSAL B',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '7691978',
    first_name: 'SANTOS',
    last_name: 'CAMACHO GARZON',
    position: 'OBRERO B',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3149280,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
  
    identification_number: '83169485',
    first_name: 'FREDY ISAURO',
    last_name: 'BONILLA ALDANA',
    position: 'OBRERO B',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3149280,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
];

export async function seedEmployeesSanFrancisco(dataSource: DataSource): Promise<void> {
  const employeeRepo = dataSource.getRepository(Employee);
  const fieldRepo = dataSource.getRepository(Field);

  const field = await fieldRepo.findOneBy({ id: FIELD_ID });
  if (!field) {
    throw new Error(`Field with id ${FIELD_ID} not found. Run field seed first.`);
  }

  let created = 0;
  let skipped = 0;

  for (const data of employeesData) {
    if (data.identification_number === 'PENDIENTE') {
      console.warn(
        `⚠️  Skipping ${data.first_name} ${data.last_name} — identification_number inválido en el Excel`,
      );
      continue;
    }

    const exists = await employeeRepo.findOneBy({
      identification_number: data.identification_number,
    });

    if (exists) {
      skipped++;
      continue;
    }

    const employee = employeeRepo.create({ ...data, field });
    await employeeRepo.save(employee);
    created++;
  }

  console.log(
    `✅ San Francisco seed complete — created: ${created}, skipped (already exist): ${skipped}`,
  );
}