import { DataSource } from 'typeorm';
import { Employee,ScheduleType } from '@/plants/employees/entities/employee.entity';
import { Field } from '@/plants/fields/entities/field.entity';

const FIELD_ID = '5ee5a18e-bea4-4c54-9d43-51b6320a3ba6';

const employeesData: Omit<
  Employee,
  'id' | 'field' | 'created_by' | 'created_at' | 'updated_at' | 'deleted_at'
>[] = [
  // ── 6x6 ──────────────────────────────────────────────────────────────────
  {
    identification_number: '14254326',
    first_name: 'FRANCISCO',
    last_name: 'MORENO ORJUELA',
    position: 'OPERADOR MAYOR C',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 5519910,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '83088221',
    first_name: 'CESAR OMAR',
    last_name: 'ZAMORA SANCHEZ',
    position: 'OPERADOR MAYOR C',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 5519910,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1075262809',
    first_name: 'JOSEPH STEVEN',
    last_name: 'PEREZ ROJAS',
    position: 'OPERADOR MAYOR C',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 5519910,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1075240404',
    first_name: 'SANTIAGO',
    last_name: 'PERDOMO CERQUERA',
    position: 'OPERADOR MAYOR C',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 5519910,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '13544064',
    first_name: 'WILLIAM',
    last_name: 'RAMIREZ',
    position: 'OPERADOR MENOR D',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4077630,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1075276437',
    first_name: 'JUAN DAVID',
    last_name: 'MACHADO CASTIBLANCO',
    position: 'OPERADOR MENOR D',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '83093155',
    first_name: 'OSCAR JULIAN',
    last_name: 'GUTIERREZ',
    position: 'OPERADOR MENOR D',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4077630,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '7701176',
    first_name: 'RAUL',
    last_name: 'HORTA CAMPOS',
    position: 'OPERADOR MENOR D',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4472820,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1075300108',
    first_name: 'FELIPE ASDRUBAL',
    last_name: 'PINZON',
    position: 'RECORREDOR B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '12119409',
    first_name: 'JOSE MILLER',
    last_name: 'ESCOBAR TELLO',
    position: 'RECORREDOR B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '7707329',
    first_name: 'NOEL',
    last_name: 'RAMIREZ SANCHEZ',
    position: 'RECORREDOR B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '7717146',
    first_name: 'YESID',
    last_name: 'GARCIA RODRIGUEZ',
    position: 'RECORREDOR B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1081183493',
    first_name: 'ANDRES FELIPE',
    last_name: 'ALARCON',
    position: 'OPERADOR MAYOR E',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4933050,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '7731517',
    first_name: 'ISRAEL',
    last_name: 'GALVIS',
    position: 'OPERADOR MAYOR E',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4933050,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '7689688',
    first_name: 'NESTOR',
    last_name: 'YUCUMA',
    position: 'OPERADOR MAYOR E',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4933050,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1004225578',
    first_name: 'LUIS FELIPE',
    last_name: 'VANEGAS CASTRO',
    position: 'OPERADOR MAYOR E',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 5519910,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '4945424',
    first_name: 'ALVARO',
    last_name: 'TOVAR PEREZ',
    position: 'RECORREDOR D',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3883320,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1075250307',
    first_name: 'LUIS ANGEL',
    last_name: 'MEDINA',
    position: 'RECORREDOR D',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4077630,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '1081182989',
    first_name: 'ELMER RICARDO',
    last_name: 'CELIS PEREZ',
    position: 'RECORREDOR D',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3883320,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '4945420',
    first_name: 'DANIEL',
    last_name: 'CASTRO PEREZ',
    position: 'RECORREDOR D',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3883320,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  {
    identification_number: '7697711',
    first_name: 'ALEXANDER',
    last_name: 'PERDOMO CHALA',
    position: 'RECORREDOR D',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3883320,
    schedules: [ScheduleType.SIX_BY_SIX],
  },
  // ── 5x2 ──────────────────────────────────────────────────────────────────
  {
    identification_number: '12137244',
    first_name: 'METODIO',
    last_name: 'GONZALEZ FIERRO',
    position: 'OPERADOR CAMION DE VACIO - OPERADOR TRANSPORTE B',
    aux_trans: false,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '12210649',
    first_name: 'JUAN CARLOS',
    last_name: 'ZABALA BASTIDAS',
    position: 'MANTENEDOR MAYOR C',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 5519910,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1075213356',
    first_name: 'JORGE',
    last_name: 'MOSQUERA CEDEÑO',
    position: 'AYUDANTE TECNICO DE SOLDADURA - AYUDANTE TECNICO C',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1075217286',
    first_name: 'ANGEL ANTONIO',
    last_name: 'HERMOSA REYES',
    position: 'CAPATAZ CUADRILLA DE PRODUCCION',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 4347090,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1075249744',
    first_name: 'DEYMER',
    last_name: 'BORRERO',
    position: 'AUXILIAR TRANSVERSAL B',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '7724899',
    first_name: 'WILFRE',
    last_name: 'CERQUERA IBARRA',
    position: 'AUXILIAR TRANSVERSAL B',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '7727124',
    first_name: 'JOSE ANYELO',
    last_name: 'CARDOZO CARVAJAL',
    position: 'AUXILIAR TRANSVERSAL B',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3698190,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1004344436',
    first_name: 'JUAN PABLO',
    last_name: 'BARRETO SÁNCHEZ',
    position: 'OBRERO B',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3149280,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '7729987',
    first_name: 'DIEGO ALEXANDER',
    last_name: 'MOLINA ARROYABE',
    position: 'HSE OPERATIVO',
    aux_trans: false,
    aux_hab: false,
    aux_ali: false,
    salario_base: 5519910,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '7728565',
    first_name: 'JUAN RICARDO',
    last_name: 'CASTRO',
    position: 'SUPERVISOR DE PRODUCCION',
    aux_trans: false,
    aux_hab: false,
    aux_ali: false,
    salario_base: 8177580,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1081182161',
    first_name: 'LISANDRO',
    last_name: 'PEREZ MEDINA',
    position: 'OPERADOR EN ENTRENAMIENTO A',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3306720,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
  {
    identification_number: '1081183348',
    first_name: 'YOLANDA',
    last_name: 'PEREZ TOVAR',
    position: 'OBRERO B',
    aux_trans: true,
    aux_hab: true,
    aux_ali: false,
    salario_base: 3149280,
    schedules: [ScheduleType.FIVE_BY_TWO],
  },
];

export async function seedEmployeesTello(dataSource: DataSource): Promise<void> {
  const employeeRepo = dataSource.getRepository(Employee);
  const fieldRepo = dataSource.getRepository(Field);

  const field = await fieldRepo.findOneBy({ id: FIELD_ID });
  if (!field) {
    throw new Error(`Field with id ${FIELD_ID} not found. Run field seed first.`);
  }

  let created = 0;
  let skipped = 0;

  for (const data of employeesData) {
    const exists = await employeeRepo.findOneBy({
      identification_number: data.identification_number,
    });

    if (exists) {
      skipped++;
      continue;
    }

    const employee = employeeRepo.create({ ...data, field });
    await employeeRepo.save(employee);
    created++;
  }

  console.log(
    `✅ Tello seed complete — created: ${created}, skipped (already exist): ${skipped}`,
  );
}